src/pages/index.tsx
=> fix: add empty dependency array to useEffect

src/pages/index.tsx
=> feat: add method links and scroll to method

public/specs/openrpc-v0.12.0.json, src/pages/index.tsx
Note: when generating off of main at 08f394d694a8bd2555af971783a39796af28b5a1, the API version was v0.11.0. I manually changed it to v0.12.0.
=> chore: add v0.12.0 specs

src/pages/index.tsx
Added the Python SDK link as discussed on Telegram.
=> add: Python-sdk link

public/specs/openrpc-v0.12.2.json, src/pages/index.tsx
=> feat: add v0.12.2 specs

public/specs/openrpc-v0.13.3.json, src/pages/index.tsx
=> feat: add v0.13.3

public/specs/openrpc-v0.13.4.json, src/pages/index.tsx
=> feat: add v0.13.4 docs

public/specs/openrpc-v0.13.5.json, src/pages/index.tsx
=> Jcs/add v0.13.5

src/pages/index.tsx
=> docs: adding new typescript client, marking others as community maintained

src/pages/index.tsx
=> fix: remove surrounding square brackets from response examples

public/specs/openrpc-v0.13.6.json, public/specs/openrpc-v0.13.7.json, src/pages/index.tsx
Adds v0.13.6 and v0.13.7 specs.
=> feat: add v0.13.6 and v0.13.7

.github/workflows/lint.yml, .github/workflows/nextjs.yml, src/components/Playground.tsx, src/lib/helper.ts
=> fix(playground): fixing build errors

src/pages/index.tsx
Adds backlinks to sidebar for tutorials.
=> feat: add backlinks to tutorials

public/specs/openrpc-v0.14.0.json, src/pages/index.tsx
Source: https://github.com/celestiaorg/celestia-node/releases/download/v0.14.0/openrpc.json
=> feat: add v0.14.0 docs

public/specs/openrpc-v0.14.1.json, src/pages/index.tsx
Adds v0.14.1 from source: <https://github.com/celestiaorg/celestia-node/releases/download/v0.14.1/openrpc.json>
=> feat: add v0.14.1

public/specs/openrpc-v0.15.0.json, src/pages/index.tsx
=> docs: add v0.15.0

public/specs/openrpc-v0.17.2.json, src/pages/index.tsx
=> docs: add v0.17.2

public/specs/openrpc-v0.20.1-mocha.json, src/pages/index.tsx
=> docs: add v0.20.1-mocha docs

public/specs/openrpc-v0.20.3.json, src/pages/index.tsx
=> docs: add v0.20.3 docs

public/specs/openrpc-v0.20.4.json, src/pages/index.tsx
Made by using the openrpc.json and removing the lines that errored: https://github.com/celestiaorg/celestia-node/issues/3993
=> docs: add v0.20.4 docs

src/components/Playground.tsx
The UI isn't clear enough in terms of telling user they **need a light node**. This fixes that.
=> feat(ui): enhance local node requirement warning in playground

public/specs/openrpc-v0.22.2.json, src/pages/index.tsx
=> docs: add v0.22.2
